In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [5]:
arr1 + arr2

array([5, 7, 9])

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [12]:
arr[0:3]

array([1, 2, 3])

In [13]:
arr.shape

(6,)

In [14]:
arr.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr

array([1, 2, 3, 4, 5, 6])

In [16]:
arr + 1

array([2, 3, 4, 5, 6, 7])

In [17]:
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])

In [18]:
np.dot(m1, m2)

array([[19, 22],
       [43, 50]])

In [19]:
np.mean(arr)

3.5

In [20]:
arr

array([1, 2, 3, 4, 5, 6])

In [21]:
np.std(arr)

1.707825127659933

In [23]:
np.random.rand(10)

array([0.25393672, 0.50178933, 0.99858148, 0.71526973, 0.79330476,
       0.9243129 , 0.65910974, 0.65514755, 0.93459802, 0.99812722])

In [24]:
arr = [1, 2, 3, np.nan, 5, 6]

In [25]:
arr

[1, 2, 3, nan, 5, 6]

In [26]:
np.isnan(arr)

array([False, False, False,  True, False, False])

In [27]:
import time

In [40]:
ls1 = list(range(100000000))
start = time.time()
sum(ls1)
end = time.time()
print(end - start)

1.1346824169158936


In [41]:
ls1 = np.array(ls1)
start = time.time()
np.sum(ls1)
end = time.time()
print(end - start)

0.07315468788146973
